### ISSUE TITLE
[Install] Class "Normalizer" not found

### ISSUE THREAD

**Issue by m-paniez9292** [Hounddd/wn-lightgallery-plugin#3]
Hi,

I have a fresh install of WinterCMS and I would like to try your plugin.

When I put `composer require hounddd/wn-lightgallery-plugin`, I have :
```
Using version ^1.0 for hounddd/wn-lightgallery-plugin
./composer.json has been updated
Running composer update hounddd/wn-lightgallery-plugin
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking hounddd/wn-lightgallery-plugin (v1.0.3)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Downloading hounddd/wn-lightgallery-plugin (v1.0.3)
PHP Fatal error:  Uncaught Error: Class "Normalizer" not found in /usr/share/php/Symfony/Component/Console/Helper/Helper.php:65
Stack trace:
#0 /usr/share/php/Symfony/Component/Console/Helper/ProgressBar.php(383): Symfony\Component\Console\Helper\Helper::width()
#1 /usr/share/php/Symfony/Component/Console/Helper/ProgressBar.php(322): Symfony\Component\Console\Helper\ProgressBar->setMaxSteps()
#2 /usr/share/php/Composer/Util/Loop.php(89): Symfony\Component\Console\Helper\ProgressBar->start()
#3 /usr/share/php/Composer/Installer/InstallationManager.php(497): Composer\Util\Loop->wait()
#4 /usr/share/php/Composer/Installer/InstallationManager.php(362): Composer\Installer\InstallationManager->waitOnPromises()
#5 /usr/share/php/Composer/Installer/InstallationManager.php(282): Composer\Installer\InstallationManager->downloadAndExecuteBatch()
#6 /usr/share/php/Composer/Installer.php(754): Composer\Installer\InstallationManager->execute()
#7 /usr/share/php/Composer/Installer.php(583): Composer\Installer->doInstall()
#8 /usr/share/php/Composer/Installer.php(279): Composer\Installer->doUpdate()
#9 /usr/share/php/Composer/Command/RequireCommand.php(430): Composer\Installer->run()
#10 /usr/share/php/Composer/Command/RequireCommand.php(285): Composer\Command\RequireCommand->doUpdate()
#11 /usr/share/php/Symfony/Component/Console/Command/Command.php(298): Composer\Command\RequireCommand->execute()
#12 /usr/share/php/Symfony/Component/Console/Application.php(1015): Symfony\Component\Console\Command\Command->run()
#13 /usr/share/php/Symfony/Component/Console/Application.php(299): Symfony\Component\Console\Application->doRunCommand()
#14 /usr/share/php/Composer/Console/Application.php(336): Symfony\Component\Console\Application->doRun()
#15 /usr/share/php/Symfony/Component/Console/Application.php(171): Composer\Console\Application->doRun()
#16 /usr/share/php/Composer/Console/Application.php(131): Symfony\Component\Console\Application->run()
#17 /usr/bin/composer(84): Composer\Console\Application->run()
#18 {main}
  thrown in /usr/share/php/Symfony/Component/Console/Helper/Helper.php on line 65

Fatal error: Uncaught Error: Class "Normalizer" not found in /usr/share/php/Symfony/Component/Console/Helper/Helper.php:65
Stack trace:
#0 /usr/share/php/Symfony/Component/Console/Helper/ProgressBar.php(383): Symfony\Component\Console\Helper\Helper::width()
#1 /usr/share/php/Symfony/Component/Console/Helper/ProgressBar.php(322): Symfony\Component\Console\Helper\ProgressBar->setMaxSteps()
#2 /usr/share/php/Composer/Util/Loop.php(89): Symfony\Component\Console\Helper\ProgressBar->start()
#3 /usr/share/php/Composer/Installer/InstallationManager.php(497): Composer\Util\Loop->wait()
#4 /usr/share/php/Composer/Installer/InstallationManager.php(362): Composer\Installer\InstallationManager->waitOnPromises()
#5 /usr/share/php/Composer/Installer/InstallationManager.php(282): Composer\Installer\InstallationManager->downloadAndExecuteBatch()
#6 /usr/share/php/Composer/Installer.php(754): Composer\Installer\InstallationManager->execute()
#7 /usr/share/php/Composer/Installer.php(583): Composer\Installer->doInstall()
#8 /usr/share/php/Composer/Installer.php(279): Composer\Installer->doUpdate()
#9 /usr/share/php/Composer/Command/RequireCommand.php(430): Composer\Installer->run()
#10 /usr/share/php/Composer/Command/RequireCommand.php(285): Composer\Command\RequireCommand->doUpdate()
#11 /usr/share/php/Symfony/Component/Console/Command/Command.php(298): Composer\Command\RequireCommand->execute()
#12 /usr/share/php/Symfony/Component/Console/Application.php(1015): Symfony\Component\Console\Command\Command->run()
#13 /usr/share/php/Symfony/Component/Console/Application.php(299): Symfony\Component\Console\Application->doRunCommand()
#14 /usr/share/php/Composer/Console/Application.php(336): Symfony\Component\Console\Application->doRun()
#15 /usr/share/php/Symfony/Component/Console/Application.php(171): Composer\Console\Application->doRun()
#16 /usr/share/php/Composer/Console/Application.php(131): Symfony\Component\Console\Application->run()
#17 /usr/bin/composer(84): Composer\Console\Application->run()
#18 {main}
  thrown in /usr/share/php/Symfony/Component/Console/Helper/Helper.php on line 65
```

My env is :
- PHP 8.0.30
- Apache 2.4.52

Thanks

**Comment by m-paniez9292** [comment]
Re,

I found, I haven't install intl php extension.

Thanks
